#!/usr/bin/env python3
"""Merge new Kannada and Malayalam translations into the existing locale files."""
import json
import os

# Kannada translations for the 267 new keys
KN_NEW = {
    "notifications.emptyTitleAll": "ಇನ್ನೂ ಯಾವುದೇ ಅಧಿಸೂಚನೆಗಳಿಲ್ಲ",

    "search.recentSearches": "ಇತ್ತೀಚಿನ ಹುಡುಕಾಟಗಳು",
    "search.clearAll": "ಎಲ್ಲಾ ತೆರವುಗೊಳಿಸಿ",
    "search.popularSearches": "ಜನಪ್ರಿಯ ಹುಡುಕಾಟಗಳು",
    "search.searchTips": "ಹುಡುಕಾಟ ಸಲಹೆಗಳು",
    "search.tipBody": "ಕೈಮುಕ್ತ ಖರೀದಿಗಾಗಿ ಧ್ವನಿ ಹುಡುಕಾಟ (ಮೈಕ್ ಐಕಾನ್) ಬಳಸಿ. ಉತ್ಪನ್ನದ ಹೆಸರು, ಬ್ರಾಂಡ್ ಅಥವಾ ವರ್ಗದಿಂದ ಹುಡುಕಿ.",
    "search.listening": "ಆಲಿಸುತ್ತಿದೆ...",
    "search.heard": "ಕೇಳಿಸಿದ್ದು:",
    "search.sayProduct": "ಉತ್ಪನ್ನದ ಹೆಸರು ಅಥವಾ ಕೀವರ್ಡ್ ಹೇಳಿ",
    "search.stopVoice": "ಧ್ವನಿ ಹುಡುಕಾಟ ನಿಲ್ಲಿಸಿ",
    "search.voiceSearch": "ಧ್ವನಿ ಹುಡುಕಾಟ",
    "search.voiceNotSupported": "ಈ ಬ್ರೌಸರ್‌ನಲ್ಲಿ ಧ್ವನಿ ಹುಡುಕಾಟ ಬೆಂಬಲಿತವಾಗಿಲ್ಲ. ದಯವಿಟ್ಟು Chrome ಅಥವಾ Safari ಪ್ರಯತ್ನಿಸಿ.",
    "search.noSpeech": "ಯಾವುದೇ ಧ್ವನಿ ಪತ್ತೆಯಾಗಿಲ್ಲ. ದಯವಿಟ್ಟು ಮರುಪ್ರಯತ್ನಿಸಿ.",
    "search.micDenied": "ಮೈಕ್ ಪ್ರವೇಶ ನಿರಾಕರಿಸಲಾಗಿದೆ. ದಯವಿಟ್ಟು ಮೈಕ್ ಅನುಮತಿ ನೀಡಿ.",
    "search.voiceError": "ಧ್ವನಿ ಹುಡುಕಾಟ ದೋಷ: {error}",

    "productDetail.productNotFound": "ಉತ್ಪನ್ನ ಕಂಡುಬಂದಿಲ್ಲ",
    "productDetail.productUnavailable": "ಈ ಉತ್ಪನ್ನ ತೆಗೆದುಹಾಕಲಾಗಿರಬಹುದು ಅಥವಾ ಲಭ್ಯವಿಲ್ಲ.",
    "productDetail.failedToLoad": "ಲೋಡ್ ಮಾಡಲು ವಿಫಲವಾಗಿದೆ",
    "productDetail.ratingsCount": "{count} ರೇಟಿಂಗ್",
    "productDetail.ratingsCount_plural": "{count} ರೇಟಿಂಗ್‌ಗಳು",
    "productDetail.noRatings": "ಇನ್ನೂ ಯಾವುದೇ ರೇಟಿಂಗ್ ಇಲ್ಲ",
    "productDetail.percentOff": "{percent}% ರಿಯಾಯಿತಿ",
    "productDetail.inclusiveOfTaxes": "ಎಲ್ಲಾ ತೆರಿಗೆಗಳು ಸೇರಿದಂತೆ",
    "productDetail.emiFrom": "{amount}/ತಿಂಗಳಿನಿಂದ EMI",
    "productDetail.deliveryCharge": "ವಿತರಣೆ: {amount}",
    "productDetail.deliveryChargeApplies": "ವಿತರಣಾ ಶುಲ್ಕ ಅನ್ವಯಿಸುತ್ತದೆ",
    "productDetail.freeAbove": "({amount} ಮೇಲೆ ಉಚಿತ)",
    "productDetail.soldCount": "{count} ಮಾರಾಟವಾಗಿದೆ",
    "productDetail.selectAttribute": "{attribute} ಆಯ್ಕೆಮಾಡಿ",
    "productDetail.sizeChart": "ಗಾತ್ರ ಚಾರ್ಟ್",
    "productDetail.variantOutOfStock": "ಈ ವೇರಿಯಂಟ್ ಸ್ಟಾಕ್‌ನಲ್ಲಿಲ್ಲ",
    "productDetail.qty": "ಪ್ರಮಾಣ:",
    "productDetail.onlyLeft": "ಕೇವಲ {count} ಮಾತ್ರ ಉಳಿದಿವೆ!",
    "productDetail.soldBy": "ಮಾರಾಟ ಮಾಡಿದವರು",
    "productDetail.newSeller": "ಹೊಸ ಮಾರಾಟಗಾರರು",
    "productDetail.following": "ಫಾಲೋ ಮಾಡುತ್ತಿದ್ದೀರಿ",
    "productDetail.follow": "ಫಾಲೋ ಮಾಡಿ",
    "productDetail.viewSellerProfile": "{seller} ಮಾರಾಟಗಾರರ ಪ್ರೊಫೈಲ್ ನೋಡಿ",
    "productDetail.lowestPrice": "ಅತ್ಯಂತ ಕಡಿಮೆ",
    "productDetail.price": "ಬೆಲೆ",
    "productDetail.cashOn": "ಕ್ಯಾಶ್ ಆನ್",
    "productDetail.delivery": "ವಿತರಣೆ",
    "productDetail.returnsLabel": "ವಾಪಸಾತಿಗಳು",
    "productDetail.defaultReturnDays": "7-ದಿನ",
    "productDetail.warranty": "ವಾರಂಟಿ",
    "productDetail.included": "ಸೇರಿದೆ",
    "productDetail.specifications": "ವಿಶೇಷಣಗಳು",
    "productDetail.productDescription": "ಉತ್ಪನ್ನ ವಿವರಣೆ",
    "productDetail.ratingsAndReviews": "ರೇಟಿಂಗ್‌ಗಳು ಮತ್ತು ವಿಮರ್ಶೆಗಳು",
    "productDetail.writeReview": "ವಿಮರ್ಶೆ ಬರೆಯಿರಿ",
    "productDetail.editReview": "ವಿಮರ್ಶೆ ಸಂಪಾದಿಸಿ",
    "productDetail.noReviews": "ಇನ್ನೂ ಯಾವುದೇ ವಿಮರ್ಶೆಗಳಿಲ್ಲ",
    "productDetail.beFirstToReview": "ನಿಮ್ಮ ಅನುಭವ ಹಂಚಿಕೊಳ್ಳಲು ಮೊದಲಿಗರಾಗಿ",
    "productDetail.reviewsCount": "{count} ವಿಮರ್ಶೆ",
    "productDetail.reviewsCount_plural": "{count} ವಿಮರ್ಶೆಗಳು",
    "productDetail.customerImages": "ಗ್ರಾಹಕರ ಚಿತ್ರಗಳು",
    "productDetail.customerVideos": "ಗ್ರಾಹಕರ ವೀಡಿಯೊಗಳು",
    "productDetail.noReviewsMatchFilter": "ಈ ಫಿಲ್ಟರ್‌ಗೆ ಹೊಂದುವ ಯಾವುದೇ ವಿಮರ್ಶೆಗಳಿಲ್ಲ",
    "productDetail.seeMoreReviews": "ಇನ್ನಷ್ಟು ವಿಮರ್ಶೆಗಳು ನೋಡಿ ({remaining} ಉಳಿದಿವೆ)",
    "productDetail.youMightAlsoLike": "ನಿಮಗೆ ಇದೂ ಇಷ್ಟವಾಗಬಹುದು",
    "productDetail.ad": "ಜಾಹೀರಾತು",
    "productDetail.added": "ಸೇರಿಸಲಾಗಿದೆ",
    "productDetail.goToCart": "ಕಾರ್ಟ್‌ಗೆ ಹೋಗಿ",
    "productDetail.addToCart": "ಕಾರ್ಟ್‌ಗೆ ಸೇರಿಸಿ",
    "productDetail.buyNow": "ಈಗ ಖರೀದಿಸಿ",
    "productDetail.shareText": "RealCart‌ನಲ್ಲಿ {name} ನೋಡಿ! ಕೇವಲ ₹{price}",
    "productDetail.shareProduct": "ಉತ್ಪನ್ನ ಹಂಚಿಕೊಳ್ಳಿ",
    "productDetail.removeFromWishlist": "ವಿಶ್‌ಲಿಸ್ಟ್‌ನಿಂದ ತೆಗೆದುಹಾಕಿ",
    "productDetail.addToWishlist": "ವಿಶ್‌ಲಿಸ್ಟ್‌ಗೆ ಸೇರಿಸಿ",
    "productDetail.imageUnavailable": "ಚಿತ್ರ ಲಭ್ಯವಿಲ್ಲ",
    "productDetail.previousImage": "ಹಿಂದಿನ ಚಿತ್ರ",
    "productDetail.nextImage": "ಮುಂದಿನ ಚಿತ್ರ",
    "productDetail.pinchToAdjust": "{percent}% · ಸರಿಹೊಂದಿಸಲು ಪಿಂಚ್ ಮಾಡಿ",
    "productDetail.verifiedPurchase": "ಪರಿಶೀಲಿಸಿದ ಖರೀದಿ",
    "productDetail.customerAvatar": "ಗ್ರಾಹಕರ ಅವತಾರ್",
    "productDetail.reviewVideoThumb": "ವಿಮರ್ಶೆ ವೀಡಿಯೊ ಥಂಬ್‌ನೇಲ್",
    "productDetail.reviewMedia": "ವಿಮರ್ಶೆ ಮೀಡಿಯಾ",
    "productDetail.video": "ವೀಡಿಯೊ",
    "productDetail.helpfulCount": "ಉಪಯುಕ್ತ ({count})",
    "productDetail.seller": "• ಮಾರಾಟಗಾರರು",
    "productDetail.editReviewTitle": "ವಿಮರ್ಶೆ ಸಂಪಾದಿಸಿ",
    "productDetail.deleteReviewTitle": "ವಿಮರ್ಶೆ ಅಳಿಸಿ",
    "productDetail.existingPhoto": "ಈಗಿರುವ ಫೋಟೋ {index}",
    "productDetail.newPreview": "ಹೊಸ ಪ್ರಿವ್ಯೂ {index}",
    "productDetail.thumbAlt": "{name} ಥಂಬ್ {index}",
    "productDetail.mainImageAlt": "{name} - {index}",
    "productDetail.customerPhoto": "ಗ್ರಾಹಕರ ಫೋಟೋ {index}",
    "productDetail.customerVideo": "ಗ್ರಾಹಕರ ವೀಡಿಯೊ {index}",
    "productDetail.imageCounter": "{current} / {total}",
    "productDetail.videoNotSupported": "ನಿಮ್ಮ ಬ್ರೌಸರ್ ವೀಡಿಯೊ ಟ್ಯಾಗ್ ಅನ್ನು ಬೆಂಬಲಿಸುವುದಿಲ್ಲ.",

    "reviews.terrible": "ಭಯಾನಕ",
    "reviews.poor": "ಕಳಪೆ",
    "reviews.average": "ಸರಾಸರಿ",
    "reviews.good": "ಒಳ್ಳೆಯದು",
    "reviews.excellent": "ಅತ್ಯುತ್ತಮ",
    "reviews.yourRating": "ನಿಮ್ಮ ರೇಟಿಂಗ್ *",
    "reviews.reviewTitle": "ವಿಮರ್ಶೆ ಶೀರ್ಷಿಕೆ",
    "reviews.yourReview": "ನಿಮ್ಮ ವಿಮರ್ಶೆ *",
    "reviews.pros": "ಅನುಕೂಲಗಳು",
    "reviews.cons": "ಅನಾನುಕೂಲಗಳು",
    "reviews.photos": "ಫೋಟೋಗಳು",
    "reviews.videos": "ವೀಡಿಯೊಗಳು",
    "reviews.optional": "(ಐಚ್ಛಿಕ)",
    "reviews.upTo10": "(ಗರಿಷ್ಠ 10)",
    "reviews.upTo5Videos": "(ಗರಿಷ್ಠ 5, ಪ್ರತಿ ವೀಡಿಯೊ ಗರಿಷ್ಠ 30 MB)",
    "reviews.summarizePlaceholder": "ನಿಮ್ಮ ಅನುಭವ ಸಂಕ್ಷಿಪ್ತವಾಗಿ ಹೇಳಿ",
    "reviews.tellOthersPlaceholder": "ನಿಮ್ಮ ಅನುಭವ ಇತರರಿಗೆ ಹೇಳಿ (ಕನಿಷ್ಠ 10 ಅಕ್ಷರಗಳು)",
    "reviews.prosPlaceholder": "ನಿಮಗೆ ಇಷ್ಟವಾದ್ದು ಏನು?",
    "reviews.consPlaceholder": "ಸುಧಾರಿಸಬಹುದಾದ್ದು ಏನು?",
    "reviews.charCounter": "{count}/2000",
    "reviews.saved": "ಉಳಿಸಲಾಗಿದೆ",
    "reviews.add": "ಸೇರಿಸಿ",
    "reviews.supportedFormats": "ಬೆಂಬಲಿತ: MP4, WebM, MOV, AVI • ಪ್ರತಿ ವೀಡಿಯೊ ಗರಿಷ್ಠ 30 MB",
    "reviews.updating": "ಅಪ್‌ಡೇಟ್ ಮಾಡಲಾಗುತ್ತಿದೆ...",
    "reviews.submitting": "ಸಲ್ಲಿಸಲಾಗುತ್ತಿದೆ...",
    "reviews.updateReview": "ವಿಮರ್ಶೆ ಅಪ್‌ಡೇಟ್ ಮಾಡಿ",
    "reviews.submitReview": "ವಿಮರ್ಶೆ ಸಲ್ಲಿಸಿ",
    "reviews.maxPhotos": "ಗರಿಷ್ಠ 10 ಫೋಟೋಗಳಿಗೆ ಅನುಮತಿಸಲಾಗಿದೆ",
    "reviews.invalidVideoFormat": "ಅಮಾನ್ಯ ವೀಡಿಯೊ ಸ್ವರೂಪ. ಅನುಮತಿಸಲಾದ: MP4, WebM, MOV, AVI",
    "reviews.videoTooLarge": "ವೀಡಿಯೊ ತುಂಬಾ ದೊಡ್ಡದಾಗಿದೆ. ಗರಿಷ್ಠ ಗಾತ್ರ: 30 MB",
    "reviews.maxVideos": "ಗರಿಷ್ಠ 5 ವೀಡಿಯೊಗಳಿಗೆ ಅನುಮತಿಸಲಾಗಿದೆ",
    "reviews.selectRating": "ದಯವಿಟ್ಟು ರೇಟಿಂಗ್ ಆಯ್ಕೆಮಾಡಿ",
    "reviews.commentTooShort": "ಕಾಮೆಂಟ್ ಕನಿಷ್ಠ 10 ಅಕ್ಷರಗಳಾಗಿರಬೇಕು",

    "addresses.editAddress": "ವಿಳಾಸ ಸಂಪಾದಿಸಿ",
    "addresses.addNewAddress": "ಹೊಸ ವಿಳಾಸ ಸೇರಿಸಿ",
    "addresses.home": "ಮನೆ",
    "addresses.work": "ಕೆಲಸ",
    "addresses.fullNamePlaceholder": "ಪೂರ್ಣ ಹೆಸರು *",
    "addresses.mobileNumberPlaceholder": "ಮೊಬೈಲ್ ಸಂಖ್ಯೆ *",
    "addresses.addressLine1Placeholder": "ವಿಳಾಸ ಸಾಲು 1 (ಮನೆ ಸಂ., ಕಟ್ಟಡ, ಬೀದಿ) *",
    "addresses.addressLine2Placeholder": "ವಿಳಾಸ ಸಾಲು 2 (ಪ್ರದೇಶ, ಕಾಲನಿ)",
    "addresses.cityPlaceholder": "ನಗರ *",
    "addresses.statePlaceholder": "ರಾಜ್ಯ *",
    "addresses.pincodePlaceholder": "ಪಿನ್‌ಕೋಡ್ *",
    "addresses.landmarkPlaceholder": "ಹೆಗ್ಗುರುತು (ಐಚ್ಛಿಕ)",
    "addresses.setAsDefault": "ಡಿಫಾಲ್ಟ್ ವಿಳಾಸವಾಗಿ ಸೆಟ್ ಮಾಡಿ",
    "addresses.saveAddress": "ವಿಳಾಸ ಉಳಿಸಿ",
    "addresses.updateAddress": "ವಿಳಾಸ ಅಪ್‌ಡೇಟ್ ಮಾಡಿ",
    "addresses.default": "ಡಿಫಾಲ್ಟ್",
    "addresses.edit": "ಸಂಪಾದಿಸಿ",
    "addresses.delete": "ಅಳಿಸಿ",
    "addresses.setDefault": "ಡಿಫಾಲ್ಟ್ ಸೆಟ್ ಮಾಡಿ",
    "addresses.nearLandmark": ", {landmark} ಹತ್ತಿರ",
    "addresses.myAddresses": "ನನ್ನ ವಿಳಾಸಗಳು",
    "addresses.searchPlaceholder": "ವಿಳಾಸಗಳನ್ನು ಹುಡುಕಿ...",
    "addresses.savedCount": "{count} ಉಳಿಸಿದ ವಿಳಾಸ",
    "addresses.savedCount_plural": "{count} ಉಳಿಸಿದ ವಿಳಾಸಗಳು",
    "addresses.noMatching": "ಹೊಂದುವ ವಿಳಾಸಗಳಿಲ್ಲ",
    "addresses.tryDifferentSearch": "ಬೇರೆ ಹುಡುಕಾಟ ಪದ ಪ್ರಯತ್ನಿಸಿ",
    "addresses.noSavedAddresses": "ಉಳಿಸಿದ ವಿಳಾಸಗಳಿಲ್ಲ",
    "addresses.noSavedAddressesDesc": "ಪ್ರಾರಂಭಿಸಲು ನಿಮ್ಮ ಮೊದಲ ವಿತರಣಾ ವಿಳಾಸ ಸೇರಿಸಿ",
    "addresses.addAddress": "ವಿಳಾಸ ಸೇರಿಸಿ",
    "addresses.deleteConfirm": "ಈ ವಿಳಾಸವನ್ನು ಅಳಿಸಲು ಖಚಿತವಾಗಿ ಬಯಸುತ್ತೀರೆ?",

    "checkout.selectDeliveryAddress": "ವಿತರಣಾ ವಿಳಾಸ ಆಯ್ಕೆಮಾಡಿ",
    "checkout.orderSummary": "ಆರ್ಡರ್ ಸಾರಾಂಶ",
    "checkout.payment": "ಪಾವತಿ",
    "checkout.savedAddresses": "ಉಳಿಸಿದ ವಿಳಾಸಗಳು",
    "checkout.noSavedAddresses": "ಉಳಿಸಿದ ವಿಳಾಸಗಳಿಲ್ಲ. ಮುಂದುವರಿಯಲು ಒಂದನ್ನು ಸೇರಿಸಿ.",
    "checkout.addNewAddress": "ಹೊಸ ವಿಳಾಸ ಸೇರಿಸಿ",
    "checkout.continue": "ಮುಂದುವರಿಸಿ",
    "checkout.deliveryAddress": "ವಿತರಣಾ ವಿಳಾಸ",
    "checkout.change": "ಬದಲಿಸಿ",
    "checkout.mobile": "ಮೊಬೈಲ್:",
    "checkout.orderItems": "ಆರ್ಡರ್ ಐಟಂಗಳು ({count})",
    "checkout.qty": "ಪ್ರಮಾಣ:",
    "checkout.seller": "• ಮಾರಾಟಗಾರರು:",
    "checkout.deliveryOption": "ವಿತರಣಾ ಆಯ್ಕೆ",
    "checkout.selectValidAddress": "ವಿತರಣಾ ಆಯ್ಕೆಗಳನ್ನು ನೋಡಲು ಮಾನ್ಯ ವಿತರಣಾ ವಿಳಾಸ ಆಯ್ಕೆಮಾಡಿ.",
    "checkout.pleaseSelectAddress": "ದಯವಿಟ್ಟು ಮೊದಲು ವಿತರಣಾ ವಿಳಾಸ ಆಯ್ಕೆಮಾಡಿ.",
    "checkout.faster": "ವೇಗವಾಗಿ",
    "checkout.deliveryBy": "{eta} ರಂದು ವಿತರಣೆ",
    "checkout.deliveryFeeNote": "ವಿತರಣಾ ಶುಲ್ಕ ಆರ್ಡರ್ ನೀಡುವಾಗ ಸರ್ವರ್‌ನಲ್ಲಿ ಪರಿಶೀಲಿಸಲಾಗುತ್ತದೆ.",
    "checkout.continueToPayment": "ಪಾವತಿಗೆ ಮುಂದುವರಿಸಿ",
    "checkout.priceMrp": "ಬೆಲೆ (MRP, {count} ಐಟಂ)",
    "checkout.priceMrp_plural": "ಬೆಲೆ (MRP, {count} ಐಟಂಗಳು)",
    "checkout.couponLabel": "ಕೂಪನ್ ({code})",
    "checkout.totalSavings": "ಒಟ್ಟು ಉಳಿತಾಯ",
    "checkout.priceAfterDiscount": "ರಿಯಾಯಿತಿ ನಂತರದ ಬೆಲೆ",
    "checkout.deliveryCharge": "ವಿತರಣಾ ಶುಲ್ಕ",
    "checkout.estimatedDelivery": "ಅಂದಾಜು ವಿತರಣೆ",
    "checkout.codConvenienceFee": "COD ಕನ್ವೀನಿಯನ್ಸ್ ಶುಲ್ಕ",
    "checkout.platformFee": "ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ಶುಲ್ಕ",
    "checkout.totalPayable": "ಒಟ್ಟು ಪಾವತಿಸಬೇಕಾದ",
    "checkout.amountToPay": "ಪಾವತಿಸಬೇಕಾದ ಮೊತ್ತ",
    "checkout.inclusiveOfTaxes": "ಎಲ್ಲಾ ತೆರಿಗೆಗಳು ಸೇರಿದಂತೆ",
    "checkout.waitingForPayment": "ಪಾವತಿಗಾಗಿ ಕಾಯಲಾಗುತ್ತಿದೆ",
    "checkout.openUpiApp": "ನಿಮ್ಮ UPI ಆ್ಯಪ್ ತೆರೆಯಿರಿ ಮತ್ತು ಪಾವತಿ ವಿನಂತಿ ಅನುಮೋದಿಸಿ",
    "checkout.amount": "ಮೊತ್ತ",
    "checkout.checkingPaymentStatus": "ಪಾವತಿ ಸ್ಥಿತಿ ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ...",
    "checkout.securedBySsl": "256-ಬಿಟ್ SSL ಎನ್‌ಕ್ರಿಪ್ಶನ್‌ನಿಂದ ಸುರಕ್ಷಿತ",
    "checkout.cancelPayment": "ಪಾವತಿ ರದ್ದುಮಾಡಿ",
    "checkout.orderPlacedSuccess": "ಆರ್ಡರ್ ಯಶಸ್ವಿಯಾಗಿ ನೀಡಲಾಗಿದೆ!",
    "checkout.orderConfirmed": "ನಿಮ್ಮ ಆರ್ಡರ್ ದೃಢೀಕರಿಸಲಾಗಿದೆ",
    "checkout.orderId": "ಆರ್ಡರ್ ID:",
    "checkout.paymentCod": "ಪಾವತಿ: ಕ್ಯಾಶ್ ಆನ್ ಡೆಲಿವರಿ",
    "checkout.paidVia": "{method} ಮೂಲಕ ಪಾವತಿಸಲಾಗಿದೆ",
    "checkout.continueShopping": "ಖರೀದಿ ಮುಂದುವರಿಸಿ",
    "checkout.viewOrders": "ಆರ್ಡರ್‌ಗಳು ನೋಡಿ",
    "checkout.loadingBalance": "ಬ್ಯಾಲೆನ್ಸ್ ಲೋಡ್ ಮಾಡಲಾಗುತ್ತಿದೆ...",
    "checkout.available": "ಲಭ್ಯ:",
    "checkout.balanceApplied": "• ₹{amount} ಅಪ್ಲೈ ಮಾಡಲಾಗಿದೆ",
    "checkout.balanceSplit": "ಬ್ಯಾಲೆನ್ಸ್‌ನಿಂದ ₹{applied} + ಪಾವತಿ ವಿಧಾನದಿಂದ ₹{payable}",
    "checkout.selectPaymentMethod": "ಉಳಿದ ಮೊತ್ತ ಪಾವತಿಸಲು ಕೆಳಗೆ ಪಾವತಿ ವಿಧಾನ ಆಯ್ಕೆಮಾಡಿ",
    "checkout.savedPaymentMethods": "ಉಳಿಸಿದ ಪಾವತಿ ವಿಧಾನಗಳು",
    "checkout.enterCvv": "CVV ನಮೂದಿಸಿ",
    "checkout.cvvPlaceholder": "•••",
    "checkout.rbiNote": "RBI-ಅನುಸರಣೆಯ ಟೋಕನೈಸೇಶನ್ — ನಿಮ್ಮ ಸಂಪೂರ್ಣ ಕಾರ್ಡ್ ಸಂಖ್ಯೆ ಎಂದಿಗೂ ಸಂಗ್ರಹಿಸಲಾಗುವುದಿಲ್ಲ. ಈ ಪಾವತಿ ಅಧಿಕಾರಿಸಲು ಕೇವಲ CVV ಅಗತ್ಯ.",
    "checkout.useNewPaymentMethod": "ಹೊಸ ಪಾವತಿ ವಿಧಾನ ಬಳಸಿ",
    "checkout.useNewPaymentMethodDesc": "ಹೊಸ UPI / ಕಾರ್ಡ್ / ನೆಟ್ ಬ್ಯಾಂಕಿಂಗ್ / ವಾಲೆಟ್ / COD ಮೂಲಕ ಪಾವತಿಸಿ",
    "checkout.choosePaymentMethod": "ಪಾವತಿ ವಿಧಾನ ಆಯ್ಕೆಮಾಡಿ",
    "checkout.tabUpi": "UPI",
    "checkout.tabCard": "ಕಾರ್ಡ್",
    "checkout.tabNetBanking": "ನೆಟ್ ಬ್ಯಾಂಕಿಂಗ್",
    "checkout.tabWallet": "ವಾಲೆಟ್",
    "checkout.tabCod": "COD",
    "checkout.cardType": "{type} ಕಾರ್ಡ್",
    "checkout.enterUpiId": "UPI ID ನಮೂದಿಸಿ",
    "checkout.upiIdPlaceholder": "ಉದಾ., yourname@okicici ಅಥವಾ yourname@ybl",
    "checkout.upiIdInvalid": "UPI ID @ ಅನ್ನು ಹೊಂದಿರಬೇಕು (ಉದಾ., name@bank)",
    "checkout.upiIdValid": "✓ ಮಾನ್ಯ UPI ID ಸ್ವರೂಪ",
    "checkout.quickFillUpi": "UPI ಹ್ಯಾಂಡಲ್ ತ್ವರಿತ ಭರ್ತಿ",
    "checkout.acceptedCards": "ಸ್ವೀಕೃತ ಕಾರ್ಡ್‌ಗಳು:",
    "checkout.cardNumber": "ಕಾರ್ಡ್ ಸಂಖ್ಯೆ",
    "checkout.cardNumberPlaceholder": "1234 5678 9012 3456",
    "checkout.cardholderName": "ಕಾರ್ಡ್ ಹೊಂದಿರುವವರ ಹೆಸರು",
    "checkout.nameOnCardPlaceholder": "ಕಾರ್ಡ್‌ನಲ್ಲಿರುವ ಹೆಸರು",
    "checkout.expiry": "ಮುಕ್ತಾಯ",
    "checkout.expiryPlaceholder": "MM/YY",
    "checkout.cvv": "CVV",
    "checkout.cardSecurityNote": "ನಿಮ್ಮ ಕಾರ್ಡ್ ವಿವರಗಳು ಎನ್‌ಕ್ರಿಪ್ಟ್ ಮಾಡಲ್ಪಟ್ಟಿವೆ ಮತ್ತು ಸುರಕ್ಷಿತವಾಗಿ ಪ್ರಕ್ರಿಯೆಗೊಳ್ಳುತ್ತವೆ. ನಾವು ನಿಮ್ಮ ಸಂಪೂರ್ಣ ಕಾರ್ಡ್ ಮಾಹಿತಿ ಎಂದಿಗೂ ಸಂಗ್ರಹಿಸುವುದಿಲ್ಲ.",
    "checkout.popularBanks": "ಜನಪ್ರಿಯ ಬ್ಯಾಂಕ್‌ಗಳು",
    "checkout.popularWallets": "ಜನಪ್ರಿಯ ವಾಲೆಟ್‌ಗಳು",
    "checkout.codDesc": "ನಿಮ್ಮ ಆರ್ಡರ್ ಬಾಗಿಲಿಗೆ ವಿತರಿಸಿದಾಗ ಪಾವತಿಸಿ",
    "checkout.codNote": "ಸುಗಮ ವಿತರಣಾ ಅನುಭವಕ್ಕಾಗಿ ನಿಖರವಾದ ಮೊತ್ತ ಸಿದ್ಧವಾಗಿಡಿ",
    "checkout.securePaymentNote": "ನಿಮ್ಮ ಪಾವತಿ 256-ಬಿಟ್ SSL ಎನ್‌ಕ್ರಿಪ್ಶನ್‌ನೊಂದಿಗೆ ಸುರಕ್ಷಿತ. ನಾವು ನಿಮ್ಮ ಕಾರ್ಡ್ ವಿವರಗಳನ್ನು ಎಂದಿಗೂ ಸಂಗ್ರಹಿಸುವುದಿಲ್ಲ.",
    "checkout.applyCoupon": "ಕೂಪನ್ ಅಪ್ಲೈ ಮಾಡಿ",
    "checkout.youSaveAmount": "ನೀವು {amount} ಉಳಿಸುತ್ತೀರಿ!",
    "checkout.enterCouponCode": "ಕೂಪನ್ ಕೋಡ್ ನಮೂದಿಸಿ",
    "checkout.apply": "ಅಪ್ಲೈ ಮಾಡಿ",
    "checkout.couponsAvailable": "{count} ಕೂಪನ್ ಲಭ್ಯ",
    "checkout.couponsAvailable_plural": "{count} ಕೂಪನ್‌ಗಳು ಲಭ್ಯ",
    "checkout.checkingCoupons": "ಲಭ್ಯ ಕೂಪನ್‌ಗಳು ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ…",
    "checkout.safePayment": "ಸುರಕ್ಷಿತ ಪಾವತಿ",
    "checkout.savePaymentMethod": "ಮುಂದಿನ ಬಾರಿ ವೇಗವಾದ ಚೆಕ್‌ಔಟ್‌ಗಾಗಿ ಈ ಪಾವತಿ ವಿಧಾನ ಉಳಿಸಿ",
    "checkout.processingPayment": "ಪಾವತಿ ಪ್ರಕ್ರಿಯೆಯಲ್ಲಿದೆ...",
    "checkout.placingOrder": "ಆರ್ಡರ್ ನೀಡಲಾಗುತ್ತಿದೆ...",
    "checkout.placeOrderAmount": "ಆರ್ಡರ್ ನೀಡಿ • {amount}",
    "checkout.payAmount": "ಪಾವತಿಸಿ {amount}",
    "checkout.invalidCoupon": "ಅಮಾನ್ಯ ಕೂಪನ್ ಕೋಡ್",
    "checkout.couponValidateFailed": "ಕೂಪನ್ ಪ್ರಮಾಣೀಕರಿಸಲು ವಿಫಲವಾಗಿದೆ. ದಯವಿಟ್ಟು ಮರುಪ್ರಯತ್ನಿಸಿ.",
    "checkout.paymentFailed": "ಪಾವತಿ ವಿಫಲವಾಗಿದೆ. ದಯವಿಟ್ಟು ಮರುಪ್ರಯತ್ನಿಸಿ.",
    "checkout.failedToCreateOrder": "ಆರ್ಡರ್ ರಚಿಸಲು ವಿಫಲವಾಗಿದೆ",
    "checkout.unexpectedPaymentResponse": "ಅನಿರೀಕ್ಷಿತ ಪಾವತಿ ಪ್ರತಿಕ್ರಿಯೆ",
    "checkout.selectAddress": "ದಯವಿಟ್ಟು ವಿತರಣಾ ವಿಳಾಸ ಆಯ್ಕೆಮಾಡಿ",
    "checkout.cartIsEmpty": "ನಿಮ್ಮ ಕಾರ್ಟ್ ಖಾಲಿಯಾಗಿದೆ. ಆರ್ಡರ್ ನೀಡುವ ಮೊದಲು ಐಟಂಗಳನ್ನು ಸೇರಿಸಿ.",
    "checkout.selectedAddressNotFound": "ಆಯ್ಕೆಮಾಡಿದ ವಿಳಾಸ ಕಂಡುಬಂದಿಲ್ಲ",
    "checkout.selectPaymentForRemaining": "ಉಳಿದ {amount} ಗಾಗಿ ಪಾವತಿ ವಿಧಾನ ಆಯ್ಕೆಮಾಡಿ",
    "checkout.enterSavedCardCvv": "ದಯವಿಟ್ಟು ನಿಮ್ಮ ಉಳಿಸಿದ ಕಾರ್ಡ್‌ಗಾಗಿ CVV ನಮೂದಿಸಿ",
    "checkout.invalidUpiId": "ದಯವಿಟ್ಟು ಮಾನ್ಯ UPI ID ನಮೂದಿಸಿ (@ ಹೊಂದಿರಬೇಕು)",
    "checkout.invalidCardNumber": "ದಯವಿಟ್ಟು ಮಾನ್ಯ ಕಾರ್ಡ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ",
    "checkout.enterCardholderName": "ದಯವಿಟ್ಟು ಕಾರ್ಡ್ ಹೊಂದಿರುವವರ ಹೆಸರು ನಮೂದಿಸಿ",
    "checkout.invalidExpiry": "ದಯವಿಟ್ಟು ಮಾನ್ಯ ಮುಕ್ತಾಯ ದಿನಾಂಕ ನಮೂದಿಸಿ (MM/YY)",
    "checkout.invalidCvv": "ದಯವಿಟ್ಟು ಮಾನ್ಯ CVV ನಮೂದಿಸಿ",
    "checkout.selectBank": "ದಯವಿಟ್ಟು ನೆಟ್ ಬ್ಯಾಂಕಿಂಗ್‌ಗಾಗಿ ಬ್ಯಾಂಕ್ ಆಯ್ಕೆಮಾಡಿ",
    "checkout.selectWallet": "ದಯವಿಟ್ಟು ವಾಲೆಟ್ ಆಯ್ಕೆಮಾಡಿ",
    "checkout.walletPaymentFailed": "ವಾಲೆಟ್ ಪಾವತಿ ವಿಫಲವಾಗಿದೆ. ದಯವಿಟ್ಟು ಮರುಪ್ರಯತ್ನಿಸಿ.",
    "checkout.failedToPlaceOrder": "ಆರ್ಡರ್ ನೀಡಲು ವಿಫಲವಾಗಿದೆ. ದಯವಿಟ್ಟು ಮರುಪ್ರಯತ್ನಿಸಿ."
}

# Malayalam translations for the 267 new keys
ML_NEW = {
    "notifications.emptyTitleAll": "ഇതുവരെ അറിയിപ്പുകളൊന്നുമില്ല",

    "search.recentSearches": "സമീപകാല തിരയലുകൾ",
    "search.clearAll": "എല്ലാം മായ്ക്കുക",
    "search.popularSearches": "ജനപ്രിയ തിരയലുകൾ",
    "search.searchTips": "തിരയൽ നുറുങ്ങൾ",
    "search.tipBody": "കൈമുക്ത ഷോപ്പിംഗിനായി വോയ്സ് സെർച്ച് (മൈക്ക് ഐക്കൺ) ഉപയോഗിക്കുക. ഉൽപ്പന്നത്തിന്റെ പേര്, ബ്രാൻഡ്, അല്ലെങ്കിൽ വിഭാഗം ഉപയോഗിച്ച് തിരയുക.",
    "search.listening": "കേൾക്കുന്നു...",
    "search.heard": "കേട്ടത്:",
    "search.sayProduct": "ഒരു ഉൽപ്പന്ന പേര് അല്ലെങ്കിൽ കീവേഡ് പറയുക",
    "search.stopVoice": "വോയ്സ് സെർച്ച് നിർത്തുക",
    "search.voiceSearch": "വോയ്സ് സെർച്ച്",
    "search.voiceNotSupported": "ഈ ബ്രൗസറിൽ വോയ്സ് സെർച്ച് പിന്തുണയ്ക്കുന്നില്ല. ദയവായി Chrome അല്ലെങ്കിൽ Safari ശ്രമിക്കുക.",
    "search.noSpeech": "സംസാരം കണ്ടെത്തിയില്ല. ദയവായി വീണ്ടും ശ്രമിക്കുക.",
    "search.micDenied": "മൈക്ക്രോഫോൺ ആക്സസ് നിരസിച്ചു. ദയവായി മൈക്ക്രോഫോൺ അനുമതി നൽകുക.",
    "search.voiceError": "വോയ്സ് സെർച്ച് പിശക്: {error}",

    "productDetail.productNotFound": "ഉൽപ്പന്നം കണ്ടെത്തിയില്ല",
    "productDetail.productUnavailable": "ഈ ഉൽപ്പന്നം നീക്കം ചെയ്തിരിക്കാം അല്ലെങ്കിൽ ലഭ്യമല്ല.",
    "productDetail.failedToLoad": "ലോഡുചെയ്യാൻ പരാജയപ്പെട്ടു",
    "productDetail.ratingsCount": "{count} റേറ്റിംഗ്",
    "productDetail.ratingsCount_plural": "{count} റേറ്റിംഗുകൾ",
    "productDetail.noRatings": "ഇതുവരെ റേറ്റിംഗുകളൊന്നുമില്ല",
    "productDetail.percentOff": "{percent}% കിഴിവ്",
    "productDetail.inclusiveOfTaxes": "എല്ലാ നികുതികളും ഉൾപ്പെടെ",
    "productDetail.emiFrom": "{amount}/മാസം മുതൽ EMI",
    "productDetail.deliveryCharge": "ഡെലിവറി: {amount}",
    "productDetail.deliveryChargeApplies": "ഡെലിവറി നിരക്ക് ബാധകമാണ്",
    "productDetail.freeAbove": "({amount} മുകളിൽ സൗജന്യം)",
    "productDetail.soldCount": "{count} വിറ്റു",
    "productDetail.selectAttribute": "{attribute} തിരഞ്ഞെടുക്കുക",
    "productDetail.sizeChart": "സൈസ് ചാർട്ട്",
    "productDetail.variantOutOfStock": "ഈ വേരിയന്റ് സ്റ്റോക്കിലില്ല",
    "productDetail.qty": "അളവ്:",
    "productDetail.onlyLeft": "കേവലം {count} മാത്രം അവശേഷിക്കുന്നു!",
    "productDetail.soldBy": "വിറ്റത്",
    "productDetail.newSeller": "പുതിയ വിതാരകൻ",
    "productDetail.following": "പിന്തുടരുന്നു",
    "productDetail.follow": "പിന്തുടരുക",
    "productDetail.viewSellerProfile": "{seller} വിതാരകന്റെ പ്രൊഫൈൽ കാണുക",
    "productDetail.lowestPrice": "ഏറ്റവും കുറഞ്ഞ",
    "productDetail.price": "വില",
    "productDetail.cashOn": "ക്യാഷ് ഓൺ",
    "productDetail.delivery": "ഡെലിവറി",
    "productDetail.returnsLabel": "റിട്ടേണുകൾ",
    "productDetail.defaultReturnDays": "7-ദിവസം",
    "productDetail.warranty": "വാറന്റി",
    "productDetail.included": "ഉൾപ്പെടുന്നു",
    "productDetail.specifications": "സവിശേഷതകൾ",
    "productDetail.productDescription": "ഉൽപ്പന്ന വിവരണം",
    "productDetail.ratingsAndReviews": "റേറ്റിംഗുകളും അവലോകനങ്ങളും",
    "productDetail.writeReview": "ഒരു അവലോകനം എഴുതുക",
    "productDetail.editReview": "അവലോകനം എഡിറ്റ് ചെയ്യുക",
    "productDetail.noReviews": "ഇതുവരെ അവലോകനങ്ങളൊന്നുമില്ല",
    "productDetail.beFirstToReview": "നിങ്ങളുടെ അനുഭവം പങ്കിടാൻ ആദ്യത്തെയാളാവുക",
    "productDetail.reviewsCount": "{count} അവലോകനം",
    "productDetail.reviewsCount_plural": "{count} അവലോകനങ്ങൾ",
    "productDetail.customerImages": "ഉപഭോക്തൃ ചിത്രങ്ങൾ",
    "productDetail.customerVideos": "ഉപഭോക്തൃ വീഡിയോകൾ",
    "productDetail.noReviewsMatchFilter": "ഈ ഫിൽട്ടറുമായി പൊരുത്തപ്പെടുന്ന അവലോകനങ്ങളൊന്നുമില്ല",
    "productDetail.seeMoreReviews": "കൂടുതൽ അവലോകനങ്ങൾ കാണുക ({remaining} ശേഷിക്കുന്നു)",
    "productDetail.youMightAlsoLike": "നിങ്ങൾക്ക് ഇതും ഇഷ്ടപ്പെട്ടേക്കാം",
    "productDetail.ad": "പരസ്യം",
    "productDetail.added": "ചേർത്തു",
    "productDetail.goToCart": "കാർട്ടിലേക്ക് പോകുക",
    "productDetail.addToCart": "കാർട്ടിലേക്ക് ചേർക്കുക",
    "productDetail.buyNow": "ഇപ്പോൾ വാങ്ങുക",
    "productDetail.shareText": "RealCart-ൽ {name} കാണുക! കേവലം ₹{price}",
    "productDetail.shareProduct": "ഉൽപ്പന്നം പങ്കിടുക",
    "productDetail.removeFromWishlist": "വിഷ്ലിസ്റ്റിൽ നിന്ന് നീക്കം ചെയ്യുക",
    "productDetail.addToWishlist": "വിഷ്ലിസ്റ്റിലേക്ക് ചേർക്കുക",
    "productDetail.imageUnavailable": "ചിത്രം ലഭ്യമല്ല",
    "productDetail.previousImage": "മുമ്പത്തെ ചിത്രം",
    "productDetail.nextImage": "അടുത്ത ചിത്രം",
    "productDetail.pinchToAdjust": "{percent}% · ക്രമീകരിക്കാൻ പിഞ്ച് ചെയ്യുക",
    "productDetail.verifiedPurchase": "പരിശോധിച്ച വാങ്ങൽ",
    "productDetail.customerAvatar": "ഉപഭോക്തൃ അവതാർ",
    "productDetail.reviewVideoThumb": "അവലോകന വീഡിയോ തമ്പ്നെയിൽ",
    "productDetail.reviewMedia": "അവലോകന മീഡിയ",
    "productDetail.video": "വീഡിയോ",
    "productDetail.helpfulCount": "സഹായകരം ({count})",
    "productDetail.seller": "• വിതാരകൻ",
    "productDetail.editReviewTitle": "അവലോകനം എഡിറ്റ് ചെയ്യുക",
    "productDetail.deleteReviewTitle": "അവലോകനം ഇല്ലാതാക്കുക",
    "productDetail.existingPhoto": "നിലവിലുള്ള ഫോട്ടോ {index}",
    "productDetail.newPreview": "പുതിയ പ്രിവ്യൂ {index}",
    "productDetail.thumbAlt": "{name} തമ്പ് {index}",
    "productDetail.mainImageAlt": "{name} - {index}",
    "productDetail.customerPhoto": "ഉപഭോക്തൃ ഫോട്ടോ {index}",
    "productDetail.customerVideo": "ഉപഭോക്തൃ വീഡിയോ {index}",
    "productDetail.imageCounter": "{current} / {total}",
    "productDetail.videoNotSupported": "നിങ്ങളുടെ ബ്രൗസർ വീഡിയോ ടാഗ് പിന്തുണയ്ക്കുന്നില്ല.",

    "reviews.terrible": "ഭയാനകം",
    "reviews.poor": "മോശം",
    "reviews.average": "ശരാശരി",
    "reviews.good": "നല്ലത്",
    "reviews.excellent": "മികച്ചത്",
    "reviews.yourRating": "നിങ്ങളുടെ റേറ്റിംഗ് *",
    "reviews.reviewTitle": "അവലോകന ശീർഷകം",
    "reviews.yourReview": "നിങ്ങളുടെ അവലോകനം *",
    "reviews.pros": "ഗുണങ്ങൾ",
    "reviews.cons": "ദോഷങ്ങൾ",
    "reviews.photos": "ഫോട്ടോകൾ",
    "reviews.videos": "വീഡിയോകൾ",
    "reviews.optional": "(ഓപ്ഷണൽ)",
    "reviews.upTo10": "(പരമാവധി 10)",
    "reviews.upTo5Videos": "(പരമാവധി 5, ഓരോ വീഡിയോയ്ക്കും പരമാവധി 30 MB)",
    "reviews.summarizePlaceholder": "നിങ്ങളുടെ അനുഭവം ചുരുക്കുക",
    "reviews.tellOthersPlaceholder": "നിങ്ങളുടെ അനുഭവം മറ്റുള്ളവരോട് പറയുക (കുറഞ്ഞത് 10 പ്രതീകങ്ങൾ)",
    "reviews.prosPlaceholder": "എന്താണ് ഇഷ്ടപ്പെട്ടത്?",
    "reviews.consPlaceholder": "എന്താണ് മെച്ചപ്പെടുത്താൻ കഴിയുന്നത്?",
    "reviews.charCounter": "{count}/2000",
    "reviews.saved": "സേവ് ചെയ്തു",
    "reviews.add": "ചേർക്കുക",
    "reviews.supportedFormats": "പിന്തുണയ്ക്കുന്നവ: MP4, WebM, MOV, AVI • ഓരോ വീഡിയോയ്ക്കും പരമാവധി 30 MB",
    "reviews.updating": "അപ്ഡേറ്റ് ചെയ്യുന്നു...",
    "reviews.submitting": "സമർപ്പിക്കുന്നു...",
    "reviews.updateReview": "അവലോകനം അപ്ഡേറ്റ് ചെയ്യുക",
    "reviews.submitReview": "അവലോകനം സമർപ്പിക്കുക",
    "reviews.maxPhotos": "പരമാവധി 10 ഫോട്ടോകൾ അനുവദനീയമാണ്",
    "reviews.invalidVideoFormat": "അസാധുവായ വീഡിയോ ഫോർമാറ്റ്. അനുവദനീയമായത്: MP4, WebM, MOV, AVI",
    "reviews.videoTooLarge": "വീഡിയോ വളരെ വലുതാണ്. പരമാവധി വലുപ്പം: 30 MB",
    "reviews.maxVideos": "പരമാവധി 5 വീഡിയോകൾ അനുവദനീയമാണ്",
    "reviews.selectRating": "ദയവായി ഒരു റേറ്റിംഗ് തിരഞ്ഞെടുക്കുക",
    "reviews.commentTooShort": "അഭിപ്രായം കുറഞ്ഞത് 10 പ്രതീകങ്ങൾ ആയിരിക്കണം",

    "addresses.editAddress": "വിലാസം എഡിറ്റ് ചെയ്യുക",
    "addresses.addNewAddress": "പുതിയ വിലാസം ചേർക്കുക",
    "addresses.home": "വീട്",
    "addresses.work": "ജോലി",
    "addresses.fullNamePlaceholder": "പൂർണ്ണ പേര് *",
    "addresses.mobileNumberPlaceholder": "മൊബൈൽ നമ്പർ *",
    "addresses.addressLine1Placeholder": "വിലാസ വരി 1 (വീട് നമ്പർ, കെട്ടിടം, സ്ട്രീറ്റ്) *",
    "addresses.addressLine2Placeholder": "വിലാസ വരി 2 (ഏരിയ, കോളനി)",
    "addresses.cityPlaceholder": "നഗരം *",
    "addresses.statePlaceholder": "സംസ്ഥാനം *",
    "addresses.pincodePlaceholder": "പിൻകോഡ് *",
    "addresses.landmarkPlaceholder": "ലാൻഡ്മാർക്ക് (ഓപ്ഷണൽ)",
    "addresses.setAsDefault": "സ്ഥിരസ്ഥിതി വിലാസമായി സജ്ജമാക്കുക",
    "addresses.saveAddress": "വിലാസം സേവ് ചെയ്യുക",
    "addresses.updateAddress": "വിലാസം അപ്ഡേറ്റ് ചെയ്യുക",
    "addresses.default": "സ്ഥിരസ്ഥിതി",
    "addresses.edit": "എഡിറ്റ്",
    "addresses.delete": "ഇല്ലാതാക്കുക",
    "addresses.setDefault": "സ്ഥിരസ്ഥിതിയാക്കുക",
    "addresses.nearLandmark": ", {landmark}-ന് അടുത്ത്",
    "addresses.myAddresses": "എന്റെ വിലാസങ്ങൾ",
    "addresses.searchPlaceholder": "വിലാസങ്ങൾ തിരയുക...",
    "addresses.savedCount": "{count} സേവ് ചെയ്ത വിലാസം",
    "addresses.savedCount_plural": "{count} സേവ് ചെയ്ത വിലാസങ്ങൾ",
    "addresses.noMatching": "പൊരുത്തപ്പെടുന്ന വിലാസങ്ങളൊന്നുമില്ല",
    "addresses.tryDifferentSearch": "മറ്റൊരു തിരയൽ പദം പരീക്ഷിക്കുക",
    "addresses.noSavedAddresses": "സേവ് ചെയ്ത വിലാസങ്ങളൊന്നുമില്ല",
    "addresses.noSavedAddressesDesc": "ആരംഭിക്കാൻ നിങ്ങളുടെ ആദ്യ ഡെലിവറി വിലാസം ചേർക്കുക",
    "addresses.addAddress": "വിലാസം ചേർക്കുക",
    "addresses.deleteConfirm": "ഈ വിലാസം ഇല്ലാതാക്കണമെന്ന് ഉറപ്പാണോ?",

    "checkout.selectDeliveryAddress": "ഡെലിവറി വിലാസം തിരഞ്ഞെടുക്കുക",
    "checkout.orderSummary": "ഓർഡർ സംഗ്രഹം",
    "checkout.payment": "പേയ്മെന്റ്",
    "checkout.savedAddresses": "സേവ് ചെയ്ത വിലാസങ്ങൾ",
    "checkout.noSavedAddresses": "സേവ് ചെയ്ത വിലാസങ്ങളൊന്നുമില്ല. തുടരാൻ ഒന്ന് ചേർക്കുക.",
    "checkout.addNewAddress": "പുതിയ വിലാസം ചേർക്കുക",
    "checkout.continue": "തുടരുക",
    "checkout.deliveryAddress": "ഡെലിവറി വിലാസം",
    "checkout.change": "മാറ്റുക",
    "checkout.mobile": "മൊബൈൽ:",
    "checkout.orderItems": "ഓർഡർ ഇനങ്ങൾ ({count})",
    "checkout.qty": "അളവ്:",
    "checkout.seller": "• വിതാരകൻ:",
    "checkout.deliveryOption": "ഡെലിവറി ഓപ്ഷൻ",
    "checkout.selectValidAddress": "ഡെലിവറി ഓപ്ഷനുകൾ കാണാൻ സാധുവായ ഒരു ഡെലിവറി വിലാസം തിരഞ്ഞെടുക്കുക.",
    "checkout.pleaseSelectAddress": "ദയവായി ആദ്യം ഒരു ഡെലിവറി വിലാസം തിരഞ്ഞെടുക്കുക.",
    "checkout.faster": "വേഗത്തിൽ",
    "checkout.deliveryBy": "{eta} ആണ് ഡെലിവറി",
    "checkout.deliveryFeeNote": "ഓർഡർ നൽകുമ്പോൾ ഡെലിവറി ഫീ സെർവർ-സൈഡ് പരിശോധിക്കുന്നു.",
    "checkout.continueToPayment": "പേയ്മെന്റിലേക്ക് തുടരുക",
    "checkout.priceMrp": "വില (MRP, {count} ഇനം)",
    "checkout.priceMrp_plural": "വില (MRP, {count} ഇനങ്ങൾ)",
    "checkout.couponLabel": "കൂപ്പൺ ({code})",
    "checkout.totalSavings": "മൊത്തം ലാഭം",
    "checkout.priceAfterDiscount": "ഡിസ്കൗണ്ടിന് ശേഷമുള്ള വില",
    "checkout.deliveryCharge": "ഡെലിവറി നിരക്ക്",
    "checkout.estimatedDelivery": "ഏകദേശം ഡെലിവറി",
    "checkout.codConvenienceFee": "COD കൺവീനിയൻസ് ഫീ",
    "checkout.platformFee": "പ്ലാറ്റ്ഫോം ഫീ",
    "checkout.totalPayable": "മൊത്തം അടയ്ക്കേണ്ടത്",
    "checkout.amountToPay": "അടയ്ക്കേണ്ട തുക",
    "checkout.inclusiveOfTaxes": "എല്ലാ നികുതികളും ഉൾപ്പെടെ",
    "checkout.waitingForPayment": "പേയ്മെന്റിനായി കാത്തിരിക്കുന്നു",
    "checkout.openUpiApp": "നിങ്ങളുടെ UPI ആപ്പ് തുറക്കുക, പേയ്മെന്റ് അഭ്യർത്ഥന അംഗീകരിക്കുക",
    "checkout.amount": "തുക",
    "checkout.checkingPaymentStatus": "പേയ്മെന്റ് നില പരിശോധിക്കുന്നു...",
    "checkout.securedBySsl": "256-ബിറ്റ് SSL എൻക്രിപ്ഷൻ ഉപയോഗിച്ച് സുരക്ഷിതം",
    "checkout.cancelPayment": "പേയ്മെന്റ് റദ്ദാക്കുക",
    "checkout.orderPlacedSuccess": "ഓർഡർ വിജയകരമായി നൽകി!",
    "checkout.orderConfirmed": "നിങ്ങളുടെ ഓർഡർ സ്ഥിരീകരിച്ചു",
    "checkout.orderId": "ഓർഡർ ID:",
    "checkout.paymentCod": "പേയ്മെന്റ്: ക്യാഷ് ഓൺ ഡെലിവറി",
    "checkout.paidVia": "{method} വഴി അടച്ചു",
    "checkout.continueShopping": "ഷോപ്പിംഗ് തുടരുക",
    "checkout.viewOrders": "ഓർഡറുകൾ കാണുക",
    "checkout.loadingBalance": "ബാലൻസ് ലോഡുചെയ്യുന്നു...",
    "checkout.available": "ലഭ്യമാണ്:",
    "checkout.balanceApplied": "• ₹{amount} പ്രയോഗിച്ചു",
    "checkout.balanceSplit": "ബാലൻസിൽ നിന്ന് ₹{applied} + പേയ്മെന്റ് രീതിയിലൂടെ ₹{payable}",
    "checkout.selectPaymentMethod": "ശേഷിക്കുന്ന തുക അടയ്ക്കാൻ താഴെ ഒരു പേയ്മെന്റ് രീതി തിരഞ്ഞെടുക്കുക",
    "checkout.savedPaymentMethods": "സേവ് ചെയ്ത പേയ്മെന്റ് രീതികൾ",
    "checkout.enterCvv": "CVV നൽകുക",
    "checkout.cvvPlaceholder": "•••",
    "checkout.rbiNote": "RBI-അനുസൃത ടോക്കനൈസേഷൻ — നിങ്ങളുടെ പൂർണ്ണ കാർഡ് നമ്പർ ഒരിക്കലും സംഭരിക്കപ്പെടുന്നില്ല. ഈ പേയ്മെന്റ് അംഗീകരിക്കാൻ CVV മാത്രമേ ആവശ്യം.",
    "checkout.useNewPaymentMethod": "പുതിയ പേയ്മെന്റ് രീതി ഉപയോഗിക്കുക",
    "checkout.useNewPaymentMethodDesc": "പുതിയ UPI / കാർഡ് / നെറ്റ് ബാങ്കിംഗ് / വാലറ്റ് / COD ഉപയോഗിച്ച് അടയ്ക്കുക",
    "checkout.choosePaymentMethod": "പേയ്മെന്റ് രീതി തിരഞ്ഞെടുക്കുക",
    "checkout.tabUpi": "UPI",
    "checkout.tabCard": "കാർഡ്",
    "checkout.tabNetBanking": "നെറ്റ് ബാങ്കിംഗ്",
    "checkout.tabWallet": "വാലറ്റ്",
    "checkout.tabCod": "COD",
    "checkout.cardType": "{type} കാർഡ്",
    "checkout.enterUpiId": "UPI ID നൽകുക",
    "checkout.upiIdPlaceholder": "ഉദാ., yourname@okicici അല്ലെങ്കിൽ yourname@ybl",
    "checkout.upiIdInvalid": "UPI ID-യിൽ @ ഉണ്ടായിരിക്കണം (ഉദാ., name@bank)",
    "checkout.upiIdValid": "✓ സാധുവായ UPI ID ഫോർമാറ്റ്",
    "checkout.quickFillUpi": "UPI ഹാൻഡിൽ വേഗത്തിൽ പൂരിപ്പിക്കുക",
    "checkout.acceptedCards": "സ്വീകാര്യമായ കാർഡുകൾ:",
    "checkout.cardNumber": "കാർഡ് നമ്പർ",
    "checkout.cardNumberPlaceholder": "1234 5678 9012 3456",
    "checkout.cardholderName": "കാർഡുടമയുടെ പേര്",
    "checkout.nameOnCardPlaceholder": "കാർഡിലെ പേര്",
    "checkout.expiry": "കാലഹരണം",
    "checkout.expiryPlaceholder": "MM/YY",
    "checkout.cvv": "CVV",
    "checkout.cardSecurityNote": "നിങ്ങളുടെ കാർഡ് വിശദാംശങ്ങൾ എൻക്രിപ്റ്റ് ചെയ്ത് സുരക്ഷിതമായി പ്രോസസ്സ് ചെയ്യുന്നു. നിങ്ങളുടെ പൂർണ്ണ കാർഡ് വിവരങ്ങൾ ഞങ്ങൾ ഒരിക്കലും സംഭരിക്കുന്നില്ല.",
    "checkout.popularBanks": "ജനപ്രിയ ബാങ്കുകൾ",
    "checkout.popularWallets": "ജനപ്രിയ വാലറ്റുകൾ",
    "checkout.codDesc": "നിങ്ങളുടെ ഓർഡർ വാതിലിൽ ഡെലിവർ ചെയ്യുമ്പോൾ അടയ്ക്കുക",
    "checkout.codNote": "സുഗമമായ ഡെലിവറി അനുഭവത്തിനായി കൃത്യമായ തുക തയ്യാറാക്കുക",
    "checkout.securePaymentNote": "നിങ്ങളുടെ പേയ്മെന്റ് 256-ബിറ്റ് SSL എൻക്രിപ്ഷനോടെ സുരക്ഷിതമാണ്. നിങ്ങളുടെ കാർഡ് വിശദാംശങ്ങൾ ഞങ്ങൾ ഒരിക്കലും സംഭരിക്കുന്നില്ല.",
    "checkout.applyCoupon": "കൂപ്പൺ പ്രയോഗിക്കുക",
    "checkout.youSaveAmount": "നിങ്ങൾ {amount} ലാഭിക്കും!",
    "checkout.enterCouponCode": "കൂപ്പൺ കോഡ് നൽകുക",
    "checkout.apply": "പ്രയോഗിക്കുക",
    "checkout.couponsAvailable": "{count} കൂപ്പൺ ലഭ്യമാണ്",
    "checkout.couponsAvailable_plural": "{count} കൂപ്പണുകൾ ലഭ്യമാണ്",
    "checkout.checkingCoupons": "ലഭ്യമായ കൂപ്പണുകൾ പരിശോധിക്കുന്നു…",
    "checkout.safePayment": "സുരക്ഷിത പേയ്മെന്റ്",
    "checkout.savePaymentMethod": "അടുത്ത തവണ വേഗമേറിയ ചെക്കൗട്ടിനായി ഈ പേയ്മെന്റ് രീതി സേവ് ചെയ്യുക",
    "checkout.processingPayment": "പേയ്മെന്റ് പ്രോസസ്സ് ചെയ്യുന്നു...",
    "checkout.placingOrder": "ഓർഡർ നൽകുന്നു...",
    "checkout.placeOrderAmount": "ഓർഡർ നൽകുക • {amount}",
    "checkout.payAmount": "അടയ്ക്കുക {amount}",
    "checkout.invalidCoupon": "അസാധുവായ കൂപ്പൺ കോഡ്",
    "checkout.couponValidateFailed": "കൂപ്പൺ പരിശോധിക്കാൻ പരാജയപ്പെട്ടു. ദയവായി വീണ്ടും ശ്രമിക്കുക.",
    "checkout.paymentFailed": "പേയ്മെന്റ് പരാജയപ്പെട്ടു. ദയവായി വീണ്ടും ശ്രമിക്കുക.",
    "checkout.failedToCreateOrder": "ഓർഡർ സൃഷ്ടിക്കാൻ പരാജയപ്പെട്ടു",
    "checkout.unexpectedPaymentResponse": "അപ്രതീക്ഷിത പേയ്മെന്റ് പ്രതികരണം",
    "checkout.selectAddress": "ദയവായി ഒരു ഡെലിവറി വിലാസം തിരഞ്ഞെടുക്കുക",
    "checkout.cartIsEmpty": "നിങ്ങളുടെ കാർട്ട് ശൂന്യമാണ്. ഓർഡർ നൽകുന്നതിന് മുമ്പ് ഇനങ്ങൾ ചേർക്കുക.",
    "checkout.selectedAddressNotFound": "തിരഞ്ഞെടുത്ത വിലാസം കണ്ടെത്തിയില്ല",
    "checkout.selectPaymentForRemaining": "ശേഷിക്കുന്ന {amount}-നായി ഒരു പേയ്മെന്റ് രീതി തിരഞ്ഞെടുക്കുക",
    "checkout.enterSavedCardCvv": "ദയവായി നിങ്ങളുടെ സേവ് ചെയ്ത കാർഡിനായി CVV നൽകുക",
    "checkout.invalidUpiId": "ദയവായി സാധുവായ UPI ID നൽകുക (@ ഉണ്ടായിരിക്കണം)",
    "checkout.invalidCardNumber": "ദയവായി സാധുവായ കാർഡ് നമ്പർ നൽകുക",
    "checkout.enterCardholderName": "ദയവായി കാർഡുടമയുടെ പേര് നൽകുക",
    "checkout.invalidExpiry": "ദയവായി സാധുവായ കാലഹരണ തീയതി നൽകുക (MM/YY)",
    "checkout.invalidCvv": "ദയവായി സാധുവായ CVV നൽകുക",
    "checkout.selectBank": "ദയവായി നെറ്റ് ബാങ്കിംഗിനായി ഒരു ബാങ്ക് തിരഞ്ഞെടുക്കുക",
    "checkout.selectWallet": "ദയവായി ഒരു വാലറ്റ് തിരഞ്ഞെടുക്കുക",
    "checkout.walletPaymentFailed": "വാലറ്റ് പേയ്മെന്റ് പരാജയപ്പെട്ടു. ദയവായി വീണ്ടും ശ്രമിക്കുക.",
    "checkout.failedToPlaceOrder": "ഓർഡർ നൽകാൻ പരാജയപ്പെട്ടു. ദയവായി വീണ്ടും ശ്രമിക്കുക."
}


def load_json(path):
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def main():
    os.chdir("/home/z/my-project")
    en = load_json("src/locales/en.json")
    en_keys = list(en.keys())

    kn_existing = load_json("src/locales/kn.json")
    ml_existing = load_json("src/locales/ml.json")

    print("Existing kn keys:", len(kn_existing))
    print("Existing ml keys:", len(ml_existing))
    print("en keys:", len(en_keys))

    en_set = set(en_keys)
    kn_set = set(kn_existing.keys())
    ml_set = set(ml_existing.keys())

    kn_missing = en_set - kn_set
    ml_missing = en_set - ml_set

    assert kn_missing == set(KN_NEW.keys()), (
        "Kannada new keys mismatch.\n"
        f"  in KN_NEW but not missing: {set(KN_NEW.keys()) - kn_missing}\n"
        f"  missing but not in KN_NEW: {kn_missing - set(KN_NEW.keys())}"
    )
    assert ml_missing == set(ML_NEW.keys()), (
        "Malayalam new keys mismatch.\n"
        f"  in ML_NEW but not missing: {set(ML_NEW.keys()) - ml_missing}\n"
        f"  missing but not in ML_NEW: {ml_missing - set(ML_NEW.keys())}"
    )

    assert not (set(KN_NEW.keys()) & kn_set), "KN_NEW overlaps existing kn keys!"
    assert not (set(ML_NEW.keys()) & ml_set), "ML_NEW overlaps existing ml keys!"

    kn_merged = {}
    for k in en_keys:
        if k in kn_existing:
            kn_merged[k] = kn_existing[k]
        else:
            kn_merged[k] = KN_NEW[k]

    ml_merged = {}
    for k in en_keys:
        if k in ml_existing:
            ml_merged[k] = ml_existing[k]
        else:
            ml_merged[k] = ML_NEW[k]

    assert len(kn_merged) == 602, f"kn_merged has {len(kn_merged)} keys, expected 602"
    assert len(ml_merged) == 602, f"ml_merged has {len(ml_merged)} keys, expected 602"
    assert set(kn_merged.keys()) == en_set, "kn_merged key set differs from en"
    assert set(ml_merged.keys()) == en_set, "ml_merged key set differs from en"

    for k, v in kn_existing.items():
        assert kn_merged[k] == v, f"kn: existing value changed for {k!r}"
    for k, v in ml_existing.items():
        assert ml_merged[k] == v, f"ml: existing value changed for {k!r}"

    import re
    placeholders = re.compile(r"\{[a-zA-Z]+\}")
    for k in en_keys:
        en_phs = set(placeholders.findall(en[k]))
        if en_phs:
            kn_phs = set(placeholders.findall(kn_merged[k]))
            ml_phs = set(placeholders.findall(ml_merged[k]))
            assert kn_phs == en_phs, f"kn placeholder mismatch for {k!r}: en={en_phs} kn={kn_phs}"
            assert ml_phs == en_phs, f"ml placeholder mismatch for {k!r}: en={en_phs} ml={ml_phs}"

    for k in en_keys:
        if k.endswith("_plural"):
            assert k in kn_merged, f"missing plural key in kn: {k}"
            assert k in ml_merged, f"missing plural key in ml: {k}"

    with open("src/locales/kn.json", "w", encoding="utf-8") as f:
        json.dump(kn_merged, f, ensure_ascii=False, indent=2)
        f.write("\n")
    with open("src/locales/ml.json", "w", encoding="utf-8") as f:
        json.dump(ml_merged, f, ensure_ascii=False, indent=2)
        f.write("\n")

    print("Wrote kn.json with", len(kn_merged), "keys")
    print("Wrote ml.json with", len(ml_merged), "keys")

    with open("src/locales/kn.json", encoding="utf-8") as f:
        kn_check = json.load(f)
    with open("src/locales/ml.json", encoding="utf-8") as f:
        ml_check = json.load(f)
    print("Re-parsed kn.json:", len(kn_check), "keys")
    print("Re-parsed ml.json:", len(ml_check), "keys")

    print("All assertions passed.")


if __name__ == "__main__":
    main()
